# Run the Infra steps (step000, step001,step002) 

# Run pre-software steps on new nodes, or all of them if we can't do just the new nodes ( pre_software playbook) 


- name: Configure all hosts with Repositories, Common Files and Set environment key
  hosts: "ONLY NEW HOSTS"
    - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_newnodesxxxx') | replace('-', '_') }}"
  become: true
  gather_facts: False
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/ssh_vars.yml"
  tags:
    - step004
    - common_tasks
  roles:
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/set-repositories", when: 'repo_method is defined' }
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/common", when: 'install_common' }
    - { role: "{{ ANSIBLE_REPO_PATH }}/roles/set_env_authorized_key", when: 'set_env_authorized_key' }


- name: PreSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tags:
    - flight_check
  tasks:
    - debug:
        msg: "Pre-Software checks completed successfully"



# Run openshift-node role on the new hosts 

- name: Configuring openshift-nodes
  gather_facts: False
  become: yes

  hosts: "ONLY NEW HOSTS"
    - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_newnodesxxxx') | replace('-', '_') }}"
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  roles:
    - "../roles/openshift-node"
  tags:
    - openshift_node_tasks
    
    
## Generate new /etc/ansible/scaleup_hosts file 
- name: Step 00x local host preparation for OpenShift deployment
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
    - "../configs/{{ env_type }}/env_secret_vars.yml"
    - "../configs/{{ env_type }}/ssh_vars.yml"
  tags:
    - generate_ansible_hosts_file
  tasks:
    - name: generate ansible hosts file
      template:
        src: "../configs/{{ env_type }}/files/scalup_hosts_template.j2" ## path is wrong
        dest: "../workdir/scaleup_hosts-{{ env_type }}-{{ guid }}"

- name: Step 00xxxxx bastion preparation for OpenShift deployment
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
  become: true
  gather_facts: False
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
    - "../configs/{{ env_type }}/env_secret_vars.yml"
    - "../configs/{{ env_type }}/ssh_vars.yml"
  tags:
    - openshift_host_templates
    - openshift_install_idm_cert
  tasks:
    - name: Copy over ansible hosts file
      copy:
        src: "../workdir/scaleup_hosts-{{ env_type }}-{{ guid }}"
        dest: /etc/ansible/scaleup_hosts

## Run Scalup playbook


- name: Run OpenShift Installer
  gather_facts: False
  become: yes
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
    - "../configs/{{ env_type }}/ssh_vars.yml"
  tags:
    - installing_openshift
  tasks: ## Change to scale up, and change inventory file
    - name: run ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
      shell: "ansible-playbook -i /etc/ansible/scalup_hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
      register: openshift_install_log
      tags:
        - openshift_installer

